# Minecraft color codes are supported for messages! Use '&' instead of 'ยง' (i.e. "&c" instead of "ยงc" for red).

message:
  invalidArguments: "&c[IMD] Correct usage format: /imd [enable/disable]"
  noPermission: "&c[IMD] You do not have permission to toggle deepslate mining speed!"
  success: "&a[IMG] Operation success!"
updateCheck: true
pluginActive: true
