# IMD now uses MiniMessage (https://docs.adventure.kyori.net/minimessage). Minecraft colors are still supported.

message:
  miniMessage:
    invalidArguments: "<red>[IMD] Correct usage format: /imd [enable/disable]</red>"
    noPermission: "<red>[IMD] You do not have permission to toggle deepslate mining speed!</red>"
    success: "<green>[IMD] Operation success!</green>"
updateCheck: true
pluginActive: true
